version: '3'

x-consul-service: &service
  image: consul:latest
  restart: always

services:
  consul-agent-1: &agent
    <<: *service
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *agent

  consul-agent-3:
    <<: *agent

  consul-server-1: &server
    <<: *agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *server

  consul-server-bootstrap:
    <<: *server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -retry-join consul-server-bootstrap -client 0.0.0.0"
