version: '3'

x-consul-image: &image
  image: consul:latest

x-consul-network: &network
  networks:
    - default

x-consul-agent: &agent
  <<: *image
  <<: *network
  command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

x-consul-server: &server
  <<: *image
  <<: *network
  command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

services:
  consul-agent-1:
    <<: *agent

  consul-agent-2:
    <<: *agent

  consul-agent-3:
    <<: *agent

  consul-server-1:
    <<: *server

  consul-server-2:
    <<: *server

  consul-server-bootstrap:
    <<: *server
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"

networks:
  default:
