# Using version 3 to provide play-with-docker badge
# You can change to version 2 without breaking.
#version: '2'
version: '3'
services:
  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=hackmd
      - POSTGRES_PASSWORD=hackmdpass
      - POSTGRES_DB=hackmd
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      backend:
    restart: always

  app:
    build: .
    image: codimd
    environment:
      - CMD_DB_URL=postgres://hackmd:hackmdpass@database:5432/hackmd
      - CMD_ALLOW_ANONYMOUS=false
    labels:
      SERVICE_TAGS: urlprefix-mattermost.localhost/
      SERVICE_3000_CHECK_HTTP: /
    expose:
      - 3000
    networks:
      backend:
    restart: always
    depends_on:
      - database

networks:
  backend:

volumes:
  database:
