version: '3.8'

services:

  web:
    build: src
    image: nexus3
    restart: unless-stopped
    expose:
      - 8081
    volumes:
      - 'web_data:/nexus-data'
    networks:
      - frontend
    labels:
      SERVICE_8081_TAGS: urlprefix-nexus3.localhost/
      SERVICE_8081_CHECK_HTTP: /

volumes:
  web_data: {}

networks:
  frontend:
    external: true
    name: consul_nexus3_frontend