version: '3'

services:
  lb:
    build: .
    image: fabio
    ports:
      - '80:9999'
      - '9998:9998'
    labels:
      SERVICE_9998_TAGS: urlprefix-fabio.localhost/
      SERVICE_9998_CHECK_HTTP: /

networks:
  default:
    external: true
    name: consul_default
