version: '3'

services:
  agent:
    build: .
    image: gliderlabs/registrator:latest
    command: -internal consul://consul-server-bootstrap:8500
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    networks:
      - consul

networks:
  consul:
    external: true
    name: consul_default
